---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-blackbox-exporter
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: prometheus-blackbox-exporter
      sourceRef:
        kind: HelmRepository
        name: prometheus-community.github.io-helm-charts
        namespace: ${workspaceNamespace}
      version: 8.2.0
  interval: 15s
  install:
    crds: CreateReplace
    remediation:
      retries: 30
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 30
  timeout: 5m0s
  releaseName: prometheus-blackbox-exporter
  valuesFrom:
    - kind: ConfigMap
      name: prometheus-blackbox-exporter-8.2.0-defaults
  targetNamespace: ${releaseNamespace}
