---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: helm.nginx.com-stable
  namespace: ${workspaceNamespace}
spec:
  interval: 10m
  timeout: 1m
  url: "https://helm.nginx.com/stable"