---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: 1password.github.io-connect-helm-charts
  namespace: ${workspaceNamespace}
spec:
  interval: 10m
  timeout: 1m
  url: "https://1password.github.io/connect-helm-charts/"