---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-arangodb-crd
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: kube-arangodb-crd
      sourceRef:
        kind: HelmRepository
        name: arangodb.github.io-kube-arangodb
        namespace: ${releaseNamespace}
      version: 1.2.23
  interval: 15s
  install:
    crds: CreateReplace
    remediation:
      retries: 30
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 30
  timeout: 5m0s
  releaseName: kube-arangodb-crd
  targetNamespace: ${releaseNamespace}
