---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress-controller
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: nginx-ingress
      sourceRef:
        kind: HelmRepository
        name: helm.nginx.com-stable
        namespace: ${workspaceNamespace}
      version: 0.15.2
  interval: 15s
  install:
    crds: CreateReplace
    remediation:
      retries: 30
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 30
  timeout: 5m0s
  releaseName: nginx-ingress-stable
  valuesFrom:
    - kind: ConfigMap
      name: nginx-ingress-controller-0.15.2-defaults
  targetNamespace: ${releaseNamespace}
