---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: oci-ghcr.io-grafana-operator
  namespace: ${workspaceNamespace}
spec:
  interval: 10m
  timeout: 1m
  url: "oci://ghcr.io/grafana-operator/helm-charts/grafana-operator"
  type: oci
