---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: sre-kommander-applications-helm-repo
  namespace: ${workspaceNamespace}
spec:
  interval: 10m
  timeout: 1m
  url: "https://mesosphere.github.io/sre-kommander-applications"