---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: 1password-connect
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: connect
      sourceRef:
        kind: HelmRepository
        name: 1password.github.io-connect-helm-charts
        namespace: ${workspaceNamespace}
      version: 1.10.0
  interval: 15s
  install:
    crds: CreateReplace
    remediation:
      retries: 30
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 30
  timeout: 5m0s
  releaseName: 1password-connect
  valuesFrom:
    - kind: ConfigMap
      name: 1password-connect-1.10.0-defaults
  targetNamespace: ${releaseNamespace}
