---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: resoto
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: resoto
      sourceRef:
        kind: HelmRepository
        name: helm.some.engineering
        namespace: ${releaseNamespace}
      version: 0.6.4
  interval: 15s
  install:
    crds: CreateReplace
    remediation:
      retries: 30
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 30
  timeout: 5m0s
  releaseName: resoto
  valuesFrom:
    - kind: ConfigMap
      name: resoto-0.6.4-defaults
  targetNamespace: ${releaseNamespace}
