{{- if .Values.externalAccountBindingSecretKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.externalAccountBindingSecretName }}
type: Opaque
data:
{{- if .Values.externalAccountBindingSecretKeyPlainText }}
    {{ externalAccountBindingSecretKeyKeyname }}: {{ externalAccountBindingSecretKey }}
{{- else -}}
    {{ externalAccountBindingSecretKeyKeyname }}: {{ externalAccountBindingSecretKey | b64enc }}
{{- end -}}
{{- end -}}