apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterIssuerName }}
  labels:
    {{- include "d2iq-internal-cluster.labels" . | nindent 4 }}
  {{- with .Values.clusterIssuerAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- with .Values.clusterIssuer }}
spec:
  {{- toYaml . | nindent 2 }}
{{- end }}