---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana-operator
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: grafana-operator
      sourceRef:
        kind: OCIRepository
        name: oci-ghcr.io-grafana-operator-5.3.0
        namespace: ${workspaceNamespace}
      version: 5.3.0
  interval: 15s
  install:
    crds: CreateReplace
    remediation:
      retries: 30
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 30
  timeout: 5m0s
  releaseName: grafana-operator
  valuesFrom:
    - kind: ConfigMap
      name: grafana-operator-5.3.0-defaults
  targetNamespace: ${releaseNamespace}
