---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: helm.some.engineering
  namespace: ${workspaceNamespace}
spec:
  interval: 10m
  timeout: 1m
  url: "https://helm.some.engineering"
